hasCJKLanguage = true

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 80

[params]
favicon = "favicon.ico"